mycalendar/events/urls.py
from django.conf.urls import url, include

from . import views

event_categories_urlpatterns = [
    url(r'^$', views.EventCategoryListView.as_view(), name='list'),
    url(r'^create/$', views.EventCategoryCreateView.as_view(), name='create'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/edit/$', views.EventCategoryUpdateView.as_view(), name='edit'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/delete/$', views.EventCategoryDeleteView.as_view(), name='delete'),
]

urlpatterns = [
    url(r'^$', views.EventCalendarView.as_view(), name='calendar'),
    url(r'^create/$', views.EventCreateView.as_view(), name='create'),
    url(r'^list-json/$', views.EventJSONListView.as_view(), name='list-json'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/edit/$', views.EventUpdateView.as_view(), name='edit'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/delete/$', views.EventDeleteView.as_view(), name='delete'),
    url(r'^categories/', include(event_categories_urlpatterns, namespace='categories')),
]

mycalendar/mycalendar/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView

from core.views import login, logout, RegisterView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='login', permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycalendar/templates/__base.html
{% load staticfiles i18n %}
<!DOCTYPE html>

<html>
<head>
    <link rel="shortcut icon" href="{% static "images/page_logo.png" %}">
    <title>
        {% block title %}{% trans "MyCalendar" %}{% endblock %}
    </title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css"/>
        <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css"/>
    {% endblock %}
    {% block javascript %}
        <script src="{% static "js/jquery.js" %}" type="text/javascript"></script>
        <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
        <script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
        <script src="{% static "js/bootstrap-datepicker.min.js" %}" type="text/javascript"></script>
        <script src="{% static "js/base.js" %}" type="text/javascript"></script>
    {% endblock %}
    {% block extra_head %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'events:calendar' %}">MyCalendar</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'friends:list' %}">Friends</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="navbar-text">{% trans "Signed in as" %} {{ request.user.username }}</li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{% trans "Menu" %}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div id="main" role="main">
    <div class="row">
        <div class="col-md-2 right-menu">
            {% block right_menu %}
            {% endblock %}
        </div>
        <div class="col-md-9">
            <h2 class="content-header">
                {% block header %}
                {% endblock %}
            </h2>

            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

mycalendar/templates/_form.html
{% csrf_token %}
{% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
{% endfor %}
{% for field in form %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {% if labels %}
            <label class="control-label" for="{{ field.id_for_label }}">{{ field.html_name | title }}</label>
        {% endif %}
        {% if 'class' in field.field.widget.attrs and 'datepicker' in field.field.widget.attrs.class %}
            <div class="datepicker-widget input-group date">
                {{ field }}
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
            </div>
            {% for error in field.errors %}
                <span class="help-block ">{{ error }}</span>
            {% endfor %}
        {% else %}
            <div>
                {{ field }}
                {% for error in field.errors %}
                    <span class="help-block ">{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endfor %}

mycalendar/templates/_messages.html
{% load i18n %}

<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>