mycalendar/events/urls.py
from django.conf.urls import url, include

from . import views

event_categories_urlpatterns = [
    url(r'^$', views.EventCategoryListView.as_view(), name='list'),
    url(r'^create/$', views.EventCategoryCreateView.as_view(), name='create'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/edit/$', views.EventCategoryUpdateView.as_view(), name='edit'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/delete/$', views.EventCategoryDeleteView.as_view(), name='delete'),
]

urlpatterns = [
    url(r'^$', views.EventCalendarView.as_view(), name='calendar'),
    url(r'^create/$', views.EventCreateView.as_view(), name='create'),
    url(r'^list-json/$', views.EventJSONListView.as_view(), name='list-json'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/edit/$', views.EventUpdateView.as_view(), name='edit'),
    url(r'^(?P<username>[\w]+)/(?P<slug>[-\w]+)/delete/$', views.EventDeleteView.as_view(), name='delete'),
    url(r'^categories/', include(event_categories_urlpatterns, namespace='categories')),
]

mycalendar/mycalendar/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView

from core.views import login, logout, RegisterView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='login', permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycalendar/events/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse

from colorful.fields import RGBColorField

from core.models import TimeStampedModel


class EventCategory(TimeStampedModel):
    """
    Category to enable grouping users events
    """
    name = models.CharField(
        _('name'),
        max_length=255,
    )
    color = RGBColorField(
        _('color')
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('user'),
        related_name='event_categories'
    )
    slug = models.SlugField()

    class Meta:
        verbose_name = _('EventCategory')
        verbose_name_plural = _('EventCategories')
        unique_together = ['name', 'user']

    def get_absolute_url(self):
        return reverse('events:categories:edit', kwargs={'username': self.user.username, 'slug': self.slug})

    def __str__(self):
        return self.name


class Event(TimeStampedModel):
    """
    Event for particular user
    """
    title = models.CharField(
        _('title'),
        max_length=255,
    )
    description = models.TextField(
        _('desription'),
        blank=True
    )
    start = models.DateTimeField(
        _('start time')
    )
    end = models.DateTimeField(
        _('end time')
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name= _('user'),
        related_name='events'
    )
    category = models.ForeignKey(
        'EventCategory',
        verbose_name= _('category'),
        related_name='events'
    )
    slug = models.SlugField()

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        unique_together = ['user', 'slug']

    def clean(self):
        if self.start and self.end and self.start - self.end > datetime.timedelta(0):
            raise ValidationError(_("End date mustn't be before start date"))

    def get_absolute_url(self):
        return reverse('events:edit', kwargs={'username': self.user.username, 'slug': self.slug})

    def __str__(self):
        return self.title

mycalendar/events/forms.py
import itertools

from django import forms
from django.forms import widgets
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Event, EventCategory


class EventForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Event.objects.none(),
                                      widget=widgets.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Event
        exclude = ('user', 'slug')
        # Adds class attributes for bootstrap styling.
        widgets = {
            'title': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'datepicker form-control'}),
            'end': forms.DateTimeInput(attrs={'class': 'datepicker form-control'}),
        }

    def __init__(self, *args, **kwargs):
        # Gets current user
        user = kwargs.pop('user')
        # Lists all user's event categories to be displayed on form.
        qs = user.event_categories.all()
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = qs

    def save(self, *args, **kwargs):
        instance = super(EventForm, self).save(commit=False)

        instance.slug = slugify(instance.title)

        # Checks slugfield max length
        max_length = Event._meta.get_field('slug').max_length
        # Cuts slug content to be proper size
        instance.slug = orig = slugify(instance.title)[:max_length]

        # Checks if slug (saved in orig temporary variable) exists already in database.
        # If exists adds "-number" to the end of slug, reserve uniqueness. Number is generated
        # as long as not exists in database. For example if slug "hello world" exists in database
        # and max slugfield length is 11 it will be replaced by hello wor-1
        for x in itertools.count(1):
            event_for_user_exists = Event.objects.filter(
                slug=instance.slug,
                user=instance.user
            ).exclude(
                id=self.instance.id
            ).exists()
            if not event_for_user_exists:
                break
            instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        instance.save()
        return instance


class EventCategoryForm(forms.ModelForm):
    class Meta:
        model = EventCategory
        exclude = ('user', 'slug')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(EventCategoryForm, self).__init__(*args, **kwargs)

    def clean(self):
        super(EventCategoryForm, self).clean()
        name = self.cleaned_data.get('name')
        # If EventCategory object is edited (instance.id other than None) exlude this one and
        # check if another exists in database.
        any_other_category_exists = EventCategory.objects.filter(
            name=name,
            user=self.user
        ).exclude(
            id=self.instance.id
        ).exists()
        # If EventCategory is create just check if another exists in database.
        any_category_exists = EventCategory.objects.filter(
            name=name,
            user=self.user
        ).exists()

        # User editing category
        if self.instance.id and name and any_other_category_exists:
            raise ValidationError(_('Category already exists'))
        # User creating category
        elif not self.instance.id and name and any_category_exists:
            raise ValidationError(_('Category already exists'))

    def save(self, *args, **kwargs):
        instance = super(EventCategoryForm, self).save(commit=False)

        instance.slug = slugify(instance.name)

        # Checks slugfield max length
        max_length = Event._meta.get_field('slug').max_length
        # Cuts slug content to be proper size
        instance.slug = orig = slugify(instance.name)[:max_length]



        for x in itertools.count(1):
            if not EventCategory.objects.filter(
                    slug=instance.slug,
                    user=instance.user
            ).exclude(
                id=self.instance.id
            ).exists():
                break
            instance.slug = "%s-%d" % (orig[:max_length - len(str(x)) - 1], x)

        instance.save()
        return instance

mycalendar/events/views.py
import datetime

from django.views import generic
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404

from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated
from braces.views import LoginRequiredMixin, UserPassesTestMixin

from .models import Event, EventCategory
from .serializers import EventSerializer
from .forms import EventForm, EventCategoryForm


class EventJSONListView(ListAPIView):
    serializer_class = EventSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        start = self.request.GET.get('start', '')
        end = self.request.GET.get('end', '')
        if self._dates_are_valid(start, end):
            return self.request.user.events.filter(
                start__range=[start, end]
            )
        return self.request.user.events.all()

    @staticmethod
    def _dates_are_valid(start, end):
        try:
            datetime.datetime.strptime(start, '%Y-%m-%d')
            datetime.datetime.strptime(end, '%Y-%m-%d')
        except ValueError:
            return False
        return True


class EventCalendarView(LoginRequiredMixin, generic.ListView):
    model = Event
    context_object_name = 'event_list'
    template_name = 'events/event_calendar.html'

    def get_queryset(self):
        return self.request.user.events.all()


class EventCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Event
    form_class = EventForm
    template_name = 'events/event_create_form.html'
    success_url = reverse_lazy('events:create')
    success_message = _('Event created')

    def get_form_kwargs(self):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(EventCreateView, self).form_valid(form)


class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, generic.UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'events/event_edit_form.html'
    success_message = _('Event updated')

    def test_func(self, user):
        event = self.get_object()
        return event.user == user

    def get_object(self, queryset=None):
        super(EventUpdateView, self).get_object()
        username = self.kwargs.get('username')
        slug = self.kwargs.get('slug')
        return get_object_or_404(
            Event,
            user__username=username,
            slug=slug
        )

    def get_form_kwargs(self):
        kwargs = super(EventUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class EventDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Event
    template_name = 'events/event_confirm_delete.html'
    success_url = reverse_lazy('events:calendar')
    context_object_name = 'event'

    def test_func(self, user):
        event = self.get_object()
        return event.user == user

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        slug = self.kwargs.get('slug')
        return get_object_or_404(
            Event,
            user__username=username,
            slug=slug
        )


class EventCategoryListView(LoginRequiredMixin, SuccessMessageMixin, generic.ListView):
    model = EventCategory
    context_object_name = 'event_category_list'
    template_name = 'events/event_category_list.html'

    def get_queryset(self):
        return self.request.user.event_categories.all()


class EventCategoryCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = EventCategory
    form_class = EventCategoryForm
    template_name = 'events/event_category_create_form.html'
    success_url = reverse_lazy('events:categories:create')
    success_message = _('Event category created')

    def get_form_kwargs(self):
        kwargs = super(EventCategoryCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(EventCategoryCreateView, self).form_valid(form)


class EventCategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, generic.UpdateView):
    model = EventCategory
    form_class = EventCategoryForm
    template_name = 'events/event_category_edit_form.html'
    success_message = _('Event category updated')

    def test_func(self, user):
        event_category = self.get_object()
        return event_category.user == user

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        slug = self.kwargs.get('slug')
        return get_object_or_404(
            EventCategory,
            user__username=username,
            slug=slug
        )

    def get_form_kwargs(self):
        kwargs = super(EventCategoryUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class EventCategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = EventCategory
    template_name = 'events/event_category_confirm_delete.html'
    success_url = reverse_lazy('events:categories:list')
    context_object_name = 'event_category'

    def test_func(self, user):
        event_category = self.get_object()
        return event_category.user == user

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        slug = self.kwargs.get('slug')
        return get_object_or_404(
            EventCategory,
            user__username=username,
            slug=slug
        )

mycalendar/templates/events/_right_menu.html
{% load i18n %}

<ul class="nav  nav-pills nav-stacked">
    <li><a href="{% url 'events:calendar' %}">{% trans "Events" %}</a></li>
    <li><a href="{% url 'events:categories:list' %}">{% trans "Event categories" %}</a></li>
    <li><a href="{% url 'events:create' %}">{% trans "Add event" %}</a></li>
    <li><a href="#">{% trans "Add friend's event" %}</a></li>
    <li><a href="{% url 'events:categories:create' %}">{% trans "Add category" %}</a></li>
</ul>

mycalendar/templates/events/event_calendar.html
{% extends '__base.html' %}

{% load staticfiles i18n bootstrap %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/events/events-calendar.css' %}"/>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/fullcalendar.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/events/events-calendar.js' %}" type="text/javascript"></script>
{% endblock %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block content %}
    <div id="calendar"></div>
{% endblock %}

mycalendar/templates/events/event_category_confirm_delete.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Delete confirmation' %}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p> {% trans "Are you sure you want to delete event category" %} "{{ event_category }}" ? </p>
        <button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
        <a href="{% url 'events:categories:list' %}" class="btn btn-default ">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

mycalendar/templates/events/event_category_create_form.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Add event category' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">

            {% include '_messages.html' %}

            <form method="post">
                {% csrf_token %}
                {{ form | bootstrap }}
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

mycalendar/templates/events/event_category_edit_form.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Edit event category' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% include '_messages.html' %}

            <form method="post">
                {% csrf_token %}
                {{ form | bootstrap }}
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                <a class="btn btn-danger"
                   href="{% url 'events:categories:delete' form.instance.user.username form.instance.slug %}">{% trans "Delete" %}</a>
            </form>
        </div>
    </div>
{% endblock %}

mycalendar/templates/events/event_category_list.html
{% extends '__base.html' %}

{% load staticfiles i18n %}


{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Event categories' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="table-responsive col-md-8">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="col-md-6"> {% trans "Name" %}</th>
                    <th class="col-md-4"> {% trans "Number of attached events" %}</th>
                    <th class="col-md-1"> {% trans "Edit" %}</th>
                    <th class="col-md-1"> {% trans "Delete" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for category in event_category_list %}
                    <tr>
                        <td>
                            {{ category.name }}
                        </td>
                        <td class="text-center">{{ category.events.all.count }}</td>
                        <td><a href="{% url 'events:categories:edit' category.user.username category.slug %}"><span
                                class="glyphicon glyphicon-pencil icon"></span></a></td>
                        <td>
                            <a href="{% url 'events:categories:delete' category.user.username category.slug %}"><span
                                    class="glyphicon glyphicon-remove icon"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

mycalendar/templates/events/event_confirm_delete.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Delete confirmation' %}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p> {% trans "Are you sure you want to delete event" %} "{{ event }}" ? </p>
        <button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
        <a href="{% url 'events:calendar' %}" class="btn btn-default">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

mycalendar/templates/events/event_create_form.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.min.css" %}" type="text/css"/>
    {{ block.super }}
{% endblock %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Add event' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% include '_messages.html' %}

            <form method="post">
                {% include '_form.html' with form=form labels=True %}
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

mycalendar/templates/events/event_edit_form.html
{% extends '__base.html' %}

{% load i18n bootstrap staticfiles %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.min.css" %}" type="text/css"/>
    {{ block.super }}
{% endblock %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block header %}
    {% trans 'Edit event' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% include '_messages.html' %}


            <form method="post">
                {% include '_form.html' with form=form labels=True %}
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                <a class="btn btn-danger"
                   href="{% url 'events:delete' form.instance.user.username form.instance.slug %}">{% trans "Delete" %}</a>
            </form>
        </div>
    </div>
{% endblock %}

mycalendar/templates/events/events_calendar.html
{% extends '__base.html' %}

{% load staticfiles i18n bootstrap %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/events/events-calendar.css' %}"/>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/fullcalendar.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/events/events-calendar.js' %}" type="text/javascript"></script>
{% endblock %}

{% block right_menu %}
    {% include 'events/_right_menu.html' %}
{% endblock %}

{% block content %}
    <div id="calendar"></div>
{% endblock %}